export const RailStations = [
    {
        name: 'Belfast',
        StationAlias: '',
        lat: '54.6123',
        lon: '-5.91744',
        code: 'BFSTC',
        id: '228',
    },
    {
        name: 'Lisburn',
        StationAlias: '',
        lat: '54.514',
        lon: '-6.04327',
        code: 'LBURN',
        id: '238',
    },
    {
        name: 'Lurgan',
        StationAlias: '',
        lat: '54.4672',
        lon: '-6.33547',
        code: 'LURGN',
        id: '241',
    },
    {
        name: 'Portadown',
        StationAlias: '',
        lat: '54.4295',
        lon: '-6.43868',
        code: 'PDOWN',
        id: '242',
    },
    {
        name: 'Sligo',
        StationAlias: '',
        lat: '54.2723',
        lon: '-8.48249',
        code: 'SLIGO',
        id: '180',
    },
    {
        name: 'Newry',
        StationAlias: '',
        lat: '54.1911',
        lon: '-6.36225',
        code: 'NEWRY',
        id: '260',
    },
    {
        name: 'Collooney',
        StationAlias: '',
        lat: '54.1871',
        lon: '-8.49453',
        code: 'COLNY',
        id: '177',
    },
    {
        name: 'Ballina',
        StationAlias: '',
        lat: '54.1085',
        lon: '-9.16146',
        code: 'BALNA',
        id: '167',
    },
    {
        name: 'Ballymote',
        StationAlias: '',
        lat: '54.0887',
        lon: '-8.52088',
        code: 'BMOTE',
        id: '176',
    },
    {
        name: 'Dundalk',
        StationAlias: '',
        lat: '54.0007',
        lon: '-6.41291',
        code: 'DDALK',
        id: '123',
    },
    {
        name: 'Foxford',
        StationAlias: '',
        lat: '53.983',
        lon: '-9.1364',
        code: 'FXFRD',
        id: '193',
    },
    {
        name: 'Boyle',
        StationAlias: '',
        lat: '53.9676',
        lon: '-8.30438',
        code: 'BOYLE',
        id: '175',
    },
    {
        name: 'Carrick on Shannon',
        StationAlias: '',
        lat: '53.9383',
        lon: '-8.10657',
        code: 'CKOSH',
        id: '174',
    },
    {
        name: 'Dromod',
        StationAlias: '',
        lat: '53.8591',
        lon: '-7.9164',
        code: 'DRMOD',
        id: '173',
    },
    {
        name: 'Castlebar',
        StationAlias: '',
        lat: '53.8471',
        lon: '-9.2873',
        code: 'CLBAR',
        id: '168',
    },
    {
        name: 'Manulla Junction',
        StationAlias: '',
        lat: '53.828',
        lon: '-9.19296',
        code: 'MNLAJ',
        id: '194',
    },
    {
        name: 'Westport',
        StationAlias: '',
        lat: '53.7955',
        lon: '-9.50885',
        code: 'WPORT',
        id: '169',
    },
    {
        name: 'Ballyhaunis',
        StationAlias: '',
        lat: '53.7616',
        lon: '-8.7584',
        code: 'BYHNS',
        id: '165',
    },
    {
        name: 'Castlerea',
        StationAlias: '',
        lat: '53.7612',
        lon: '-8.48448',
        code: 'CSREA',
        id: '164',
    },
    {
        name: 'Longford',
        StationAlias: '',
        lat: '53.7243',
        lon: '-7.79574',
        code: 'LFORD',
        id: '172',
    },
    {
        name: 'Claremorris',
        StationAlias: '',
        lat: '53.7204',
        lon: '-9.00222',
        code: 'CLMRS',
        id: '166',
    },
    {
        name: 'Drogheda',
        StationAlias: '',
        lat: '53.712',
        lon: '-6.33538',
        code: 'DGHDA',
        id: '120',
    },
    {
        name: 'Edgeworthstown',
        StationAlias: '',
        lat: '53.6888',
        lon: '-7.60299',
        code: 'ETOWN',
        id: '171',
    },
    {
        name: 'Laytown',
        StationAlias: '',
        lat: '53.6794',
        lon: '-6.24253',
        code: 'LTOWN',
        id: '119',
    },
    {
        name: 'Gormanston',
        StationAlias: '',
        lat: '53.638',
        lon: '-6.21705',
        code: 'GSTON',
        id: '117',
    },
    {
        name: 'Roscommon',
        StationAlias: '',
        lat: '53.6243',
        lon: '-8.19631',
        code: 'RSCMN',
        id: '163',
    },
    {
        name: 'Balbriggan',
        StationAlias: '',
        lat: '53.6118',
        lon: '-6.18226',
        code: 'BBRGN',
        id: '116',
    },
    {
        name: 'Skerries',
        StationAlias: '',
        lat: '53.5741',
        lon: '-6.11933',
        code: 'SKRES',
        id: '115',
    },
    {
        name: 'Mullingar',
        StationAlias: '',
        lat: '53.523',
        lon: '-7.34608',
        code: 'MLGAR',
        id: '153',
    },
    {
        name: 'Rush and Lusk',
        StationAlias: '',
        lat: '53.5201',
        lon: '-6.1439',
        code: 'RLUSK',
        id: '114',
    },
    {
        name: 'Donabate',
        StationAlias: '',
        lat: '53.4855',
        lon: '-6.15134',
        code: 'DBATE',
        id: '113',
    },
    {
        name: 'Malahide',
        StationAlias: '',
        lat: '53.4509',
        lon: '-6.15649',
        code: 'MHIDE',
        id: '112',
    },
    {
        name: 'M3 Parkway',
        StationAlias: '',
        lat: '53.4349',
        lon: '-6.46898',
        code: 'M3WAY',
        id: '86',
    },
    {
        name: 'Athlone',
        StationAlias: '',
        lat: '53.4273',
        lon: '-7.93683',
        code: 'ATLNE',
        id: '156',
    },
    {
        name: 'Dunboyne',
        StationAlias: '',
        lat: '53.4175',
        lon: '-6.46483',
        code: 'DBYNE',
        id: '85',
    },
    {
        name: 'Portmarnock',
        StationAlias: '',
        lat: '53.4169',
        lon: '-6.1512',
        code: 'PMNCK',
        id: '111',
    },
    {
        name: 'Enfield',
        StationAlias: '',
        lat: '53.4157',
        lon: '-6.83395',
        code: 'ENFLD',
        id: '83',
    },
    {
        name: 'Kilcock',
        StationAlias: '',
        lat: '53.4043',
        lon: '-6.67892',
        code: 'KCOCK',
        id: '90',
    },
    {
        name: 'Clongriffin',
        StationAlias: '',
        lat: '53.4032',
        lon: '-6.14839',
        code: 'GRGRD',
        id: '187',
    },
    {
        name: 'Sutton',
        StationAlias: '',
        lat: '53.392',
        lon: '-6.11448',
        code: 'SUTTN',
        id: '107',
    },
    {
        name: 'Bayside',
        StationAlias: '',
        lat: '53.3917',
        lon: '-6.13678',
        code: 'BYSDE',
        id: '106',
    },
    {
        name: 'Howth Junction',
        StationAlias: 'Donaghmede ( Howth Junction )',
        lat: '53.3909',
        lon: '-6.15672',
        code: 'HWTHJ',
        id: '105',
    },
    {
        name: 'Howth',
        StationAlias: '',
        lat: '53.3891',
        lon: '-6.07401',
        code: 'HOWTH',
        id: '108',
    },
    {
        name: 'Kilbarrack',
        StationAlias: '',
        lat: '53.387',
        lon: '-6.16163',
        code: 'KBRCK',
        id: '104',
    },
    {
        name: 'Hansfield',
        StationAlias: '',
        lat: '53.3853',
        lon: '-6.44205',
        code: 'HAFLD',
        id: '87',
    },
    {
        name: 'Clonsilla',
        StationAlias: '',
        lat: '53.3831',
        lon: '-6.4242',
        code: 'CLSLA',
        id: '94',
    },
    {
        name: 'Castleknock',
        StationAlias: '',
        lat: '53.3816',
        lon: '-6.37149',
        code: 'CNOCK',
        id: '96',
    },
    {
        name: 'Raheny',
        StationAlias: '',
        lat: '53.3815',
        lon: '-6.17699',
        code: 'RAHNY',
        id: '103',
    },
    {
        name: 'Harmonstown',
        StationAlias: '',
        lat: '53.3786',
        lon: '-6.19131',
        code: 'HTOWN',
        id: '102',
    },
    {
        name: 'Maynooth',
        StationAlias: '',
        lat: '53.378',
        lon: '-6.58993',
        code: 'MYNTH',
        id: '91',
    },
    {
        name: 'Navan Road Parkway',
        StationAlias: 'Phoenix Park',
        lat: '53.3777',
        lon: '-6.34591',
        code: 'PHNPK',
        id: '89',
    },
    {
        name: 'Coolmine',
        StationAlias: '',
        lat: '53.3776',
        lon: '-6.39072',
        code: 'CMINE',
        id: '95',
    },
    {
        name: 'Ashtown',
        StationAlias: '',
        lat: '53.3755',
        lon: '-6.33135',
        code: 'ASHTN',
        id: '97',
    },
    {
        name: 'Leixlip (Confey)',
        StationAlias: '',
        lat: '53.3743',
        lon: '-6.48624',
        code: 'LXCON',
        id: '93',
    },
    {
        name: 'Killester',
        StationAlias: '',
        lat: '53.373',
        lon: '-6.20442',
        code: 'KLSTR',
        id: '101',
    },
    {
        name: 'Broombridge',
        StationAlias: '',
        lat: '53.3725',
        lon: '-6.29869',
        code: 'BBRDG',
        id: '98',
    },
    {
        name: 'Leixlip (Louisa Bridge)',
        StationAlias: '',
        lat: '53.3704',
        lon: '-6.50598',
        code: 'LXLSA',
        id: '92',
    },
    {
        name: 'Drumcondra',
        StationAlias: '',
        lat: '53.3632',
        lon: '-6.25908',
        code: 'DCDRA',
        id: '99',
    },
    {
        name: 'Clontarf Road',
        StationAlias: '',
        lat: '53.3629',
        lon: '-6.22753',
        code: 'CTARF',
        id: '109',
    },
    {
        name: 'Dublin Connolly',
        StationAlias: 'Connolly',
        lat: '53.3531',
        lon: '-6.24591',
        code: 'CNLLY',
        id: '100',
    },
    {
        name: 'Docklands',
        StationAlias: '',
        lat: '53.3509',
        lon: '-6.23929',
        code: 'DCKLS',
        id: '84',
    },
    {
        name: 'Tara Street',
        StationAlias: '',
        lat: '53.347',
        lon: '-6.25425',
        code: 'TARA',
        id: '124',
    },
    {
        name: 'Dublin Heuston',
        StationAlias: 'Heuston',
        lat: '53.3464',
        lon: '-6.29461',
        code: 'HSTON',
        id: '1',
    },
    {
        name: 'Dublin Pearse',
        StationAlias: 'Pearse',
        lat: '53.3433',
        lon: '-6.24829',
        code: 'PERSE',
        id: '150',
    },
    {
        name: 'Woodlawn',
        StationAlias: '',
        lat: '53.3432',
        lon: '-8.47231',
        code: 'WLAWN',
        id: '158',
    },
    {
        name: 'Grand Canal Dock',
        StationAlias: '',
        lat: '53.3397',
        lon: '-6.23773',
        code: 'GCDK',
        id: '110',
    },
    {
        name: 'Clara',
        StationAlias: '',
        lat: '53.3395',
        lon: '-7.61596',
        code: 'CLARA',
        id: '73',
    },
    {
        name: 'Ballinasloe',
        StationAlias: '',
        lat: '53.3363',
        lon: '-8.24081',
        code: 'BSLOE',
        id: '157',
    },
    {
        name: 'Adamstown',
        StationAlias: '',
        lat: '53.3353',
        lon: '-7',
        code: 'ADAMS',
        id: '1075',
    },
    {
        name: 'Adamstown',
        StationAlias: '',
        lat: '53.3353',
        lon: '-6.45233',
        code: 'ADAMF',
        id: '975',
    },
    {
        name: 'Adamstown',
        StationAlias: '',
        lat: '53.3353',
        lon: '-6.45233',
        code: 'ADMTN',
        id: '75',
    },
    {
        name: 'Lansdowne Road',
        StationAlias: '',
        lat: '53.3347',
        lon: '-6.22979',
        code: 'LDWNE',
        id: '125',
    },
    {
        name: 'Park West and Cherry Orchard',
        StationAlias: 'Park West (Cherry Orchard )',
        lat: '53.334',
        lon: '-6.37868',
        code: 'CHORC',
        id: '76',
    },
    {
        name: 'Park West and Cherry Orchard',
        StationAlias: 'Park West (Cherry Orchard )',
        lat: '53.334',
        lon: '-6.37868',
        code: 'PWESF',
        id: '976',
    },
    {
        name: 'PARK WEST',
        StationAlias: 'Park West (Cherry Orchard )',
        lat: '53.334',
        lon: '-6.37868',
        code: 'PWESS',
        id: '1076',
    },
    {
        name: 'Clondalkin',
        StationAlias: 'Fonthill ( Clondalkin )',
        lat: '53.3334',
        lon: '-6.40628',
        code: 'CLONS',
        id: '1077',
    },
    {
        name: 'Clondalkin',
        StationAlias: 'Fonthill ( Clondalkin )',
        lat: '53.3334',
        lon: '-6.40628',
        code: 'CLONF',
        id: '977',
    },
    {
        name: 'Clondalkin',
        StationAlias: 'Fonthill ( Clondalkin )',
        lat: '53.3334',
        lon: '-6.40628',
        code: 'CLDKN',
        id: '77',
    },
    {
        name: 'Sandymount',
        StationAlias: '',
        lat: '53.3281',
        lon: '-6.22116',
        code: 'SMONT',
        id: '188',
    },
    {
        name: 'Hazelhatch',
        StationAlias: 'Celbridge (Hazelhatch )',
        lat: '53.3223',
        lon: '-6.52356',
        code: 'HZLCH',
        id: '78',
    },
    {
        name: 'Hazelhatch',
        StationAlias: 'Celbridge (Hazelhatch )',
        lat: '53.3223',
        lon: '-6.52356',
        code: 'HAZEF',
        id: '978',
    },
    {
        name: 'Hazelhatch',
        StationAlias: 'Celbridge (Hazelhatch )',
        lat: '53.3223',
        lon: '-6.52356',
        code: 'HAZES',
        id: '1078',
    },
    {
        name: 'Attymon',
        StationAlias: '',
        lat: '53.3212',
        lon: '-8.60608',
        code: 'ATMON',
        id: '159',
    },
    {
        name: 'Sydney Parade',
        StationAlias: '',
        lat: '53.3206',
        lon: '-6.21112',
        code: 'SIDNY',
        id: '126',
    },
    {
        name: 'Booterstown',
        StationAlias: '',
        lat: '53.3099',
        lon: '-6.19498',
        code: 'BTSTN',
        id: '127',
    },
    {
        name: 'Blackrock',
        StationAlias: '',
        lat: '53.3027',
        lon: '-6.17833',
        code: 'BROCK',
        id: '128',
    },
    {
        name: 'Athenry',
        StationAlias: '',
        lat: '53.3015',
        lon: '-8.74855',
        code: 'ATHRY',
        id: '162',
    },
    {
        name: 'Seapoint',
        StationAlias: '',
        lat: '53.2991',
        lon: '-6.16512',
        code: 'SEAPT',
        id: '129',
    },
    {
        name: 'Salthill and Monkstown',
        StationAlias: 'Monkstown ( Salthill )',
        lat: '53.2954',
        lon: '-6.15206',
        code: 'SHILL',
        id: '130',
    },
    {
        name: 'Dun Laoghaire',
        StationAlias: '',
        lat: '53.2951',
        lon: '-6.13498',
        code: 'DLERY',
        id: '131',
    },
    {
        name: 'Sandycove',
        StationAlias: 'Glasthule (Sandycove )',
        lat: '53.2878',
        lon: '-6.12712',
        code: 'SCOVE',
        id: '132',
    },
    {
        name: 'Glenageary',
        StationAlias: '',
        lat: '53.2812',
        lon: '-6.12289',
        code: 'GLGRY',
        id: '133',
    },
    {
        name: 'Dalkey',
        StationAlias: '',
        lat: '53.2756',
        lon: '-6.10333',
        code: 'DLKEY',
        id: '134',
    },
    {
        name: 'Oranmore',
        StationAlias: '',
        lat: '53.2751',
        lon: '-8.94792',
        code: 'ORNMR',
        id: '161',
    },
    {
        name: 'Galway',
        StationAlias: '',
        lat: '53.2736',
        lon: '-9.04696',
        code: 'GALWY',
        id: '170',
    },
    {
        name: 'Tullamore',
        StationAlias: '',
        lat: '53.2704',
        lon: '-7.49985',
        code: 'TMORE',
        id: '72',
    },
    {
        name: 'Killiney',
        StationAlias: '',
        lat: '53.2557',
        lon: '-6.11317',
        code: 'KILNY',
        id: '135',
    },
    {
        name: 'Sallins',
        StationAlias: '',
        lat: '53.2469',
        lon: '-6.66386',
        code: 'SALNS',
        id: '79',
    },
    {
        name: 'Shankill',
        StationAlias: '',
        lat: '53.2364',
        lon: '-6.11691',
        code: 'SKILL',
        id: '136',
    },
    {
        name: 'Craughwell',
        StationAlias: '',
        lat: '53.2252',
        lon: '-8.7359',
        code: 'CRGHW',
        id: '184',
    },
    {
        name: 'Woodbrook',
        StationAlias: '',
        lat: '53.22',
        lon: '-6.1101',
        code: 'WBROK',
        id: '801',
    },
    {
        name: 'Bray',
        StationAlias: '',
        lat: '53.2043',
        lon: '-6.10046',
        code: 'BRAY',
        id: '140',
    },
    {
        name: 'Newbridge',
        StationAlias: '',
        lat: '53.1855',
        lon: '-6.80807',
        code: 'NBRGE',
        id: '4',
    },
    {
        name: 'Curragh',
        StationAlias: '',
        lat: '53.1725',
        lon: '-6.86245',
        code: 'CURAH',
        id: '5',
    },
    {
        name: 'Kildare',
        StationAlias: '',
        lat: '53.163',
        lon: '-6.90802',
        code: 'KDARE',
        id: '6',
    },
    {
        name: 'Ardrahan',
        StationAlias: '',
        lat: '53.1572',
        lon: '-8.81483',
        code: 'ARHAN',
        id: '183',
    },
    {
        name: 'Portarlington',
        StationAlias: '',
        lat: '53.146',
        lon: '-7.18055',
        code: 'PTRTN',
        id: '8',
    },
    {
        name: 'Monasterevin',
        StationAlias: '',
        lat: '53.1454',
        lon: '-7.06361',
        code: 'MONVN',
        id: '7',
    },
    {
        name: 'Greystones',
        StationAlias: '',
        lat: '53.1442',
        lon: '-6.06085',
        code: 'GSTNS',
        id: '141',
    },
    {
        name: 'Kilcoole',
        StationAlias: '',
        lat: '53.107',
        lon: '-6.04112',
        code: 'KCOOL',
        id: '139',
        info: false,
    },
    {
        name: 'Gort',
        StationAlias: '',
        lat: '53.0653',
        lon: '-8.81595',
        code: 'GORT',
        id: '182',
    },
    {
        name: 'Portlaoise',
        StationAlias: '',
        lat: '53.0371',
        lon: '-7.30086',
        code: 'PTLSE',
        id: '9',
    },
    {
        name: 'Athy',
        StationAlias: '',
        lat: '52.992',
        lon: '-6.9762',
        code: 'ATHY',
        id: '45',
    },
    {
        name: 'Wicklow',
        StationAlias: '',
        lat: '52.9882',
        lon: '-6.05338',
        code: 'WLOW',
        id: '142',
    },
    {
        name: 'Roscrea',
        StationAlias: '',
        lat: '52.9607',
        lon: '-7.7941',
        code: 'RCREA',
        id: '31',
    },
    {
        name: 'Cloughjordan',
        StationAlias: '',
        lat: '52.9363',
        lon: '-8.0246',
        code: 'CJRDN',
        id: '32',
    },
    {
        name: 'Rathdrum',
        StationAlias: '',
        lat: '52.9295',
        lon: '-6.22641',
        code: 'RDRUM',
        id: '143',
    },
    {
        name: 'Ballybrophy',
        StationAlias: '',
        lat: '52.8999',
        lon: '-7.60259',
        code: 'BBRHY',
        id: '11',
    },
    {
        name: 'Nenagh',
        StationAlias: '',
        lat: '52.8605',
        lon: '-8.19471',
        code: 'NNAGH',
        id: '33',
    },
    {
        name: 'Carlow',
        StationAlias: '',
        lat: '52.8407',
        lon: '-6.92217',
        code: 'CRLOW',
        id: '46',
    },
    {
        name: 'Ennis',
        StationAlias: '',
        lat: '52.8386',
        lon: '-8.97491',
        code: 'ENNIS',
        id: '181',
    },
    {
        name: 'Arklow',
        StationAlias: '',
        lat: '52.7932',
        lon: '-6.15994',
        code: 'ARKLW',
        id: '144',
    },
    {
        name: 'Templemore',
        StationAlias: '',
        lat: '52.7878',
        lon: '-7.82293',
        code: 'TPMOR',
        id: '12',
    },
    {
        name: 'Birdhill',
        StationAlias: '',
        lat: '52.7656',
        lon: '-8.44247',
        code: 'BHILL',
        id: '34',
    },
    {
        name: 'Sixmilebridge',
        StationAlias: '',
        lat: '52.7376',
        lon: '-8.78427',
        code: 'SXMBR',
        id: '185',
    },
    {
        name: 'Castleconnell',
        StationAlias: '',
        lat: '52.7128',
        lon: '-8.49794',
        code: 'CCONL',
        id: '35',
    },
    {
        name: 'Muine Bheag',
        StationAlias: 'Bagenalstown',
        lat: '52.699',
        lon: '-6.95213',
        code: 'MNEBG',
        id: '47',
    },
    {
        name: 'Thurles',
        StationAlias: '',
        lat: '52.6766',
        lon: '-7.82189',
        code: 'THRLS',
        id: '13',
    },
    {
        name: 'Gorey',
        StationAlias: '',
        lat: '52.6712',
        lon: '-6.29195',
        code: 'GOREY',
        id: '145',
    },
    {
        name: 'Limerick',
        StationAlias: '',
        lat: '52.6587',
        lon: '-8.62397',
        code: 'LMRCK',
        id: '40',
    },
    {
        name: 'Kilkenny',
        StationAlias: '',
        lat: '52.655',
        lon: '-7.24498',
        code: 'KKNNY',
        id: '48',
    },
    {
        name: 'Thomastown',
        StationAlias: '',
        lat: '52.523',
        lon: '-7.14891',
        code: 'THTWN',
        id: '49',
    },
    {
        name: 'Enniscorthy',
        StationAlias: '',
        lat: '52.5046',
        lon: '-6.56627',
        code: 'ECRTY',
        id: '147',
    },
    {
        name: 'Limerick Junction',
        StationAlias: '',
        lat: '52.5009',
        lon: '-8.20003',
        code: 'LMRKJ',
        id: '16',
    },
    {
        name: 'Tipperary',
        StationAlias: '',
        lat: '52.4701',
        lon: '-8.1625',
        code: 'TIPRY',
        id: '41',
    },
    {
        name: 'Cahir',
        StationAlias: '',
        lat: '52.3777',
        lon: '-7.92181',
        code: 'CAHIR',
        id: '42',
    },
    {
        name: 'Clonmel',
        StationAlias: '',
        lat: '52.3611',
        lon: '-7.69936',
        code: 'CLMEL',
        id: '43',
    },
    {
        name: 'Carrick on Suir',
        StationAlias: '',
        lat: '52.3487',
        lon: '-7.40354',
        code: 'CKOSR',
        id: '44',
    },
    {
        name: 'Charleville',
        StationAlias: '',
        lat: '52.3468',
        lon: '-8.65362',
        code: 'CVILL',
        id: '19',
    },
    {
        name: 'Wexford',
        StationAlias: '',
        lat: '52.3434',
        lon: '-6.4636',
        code: 'WXFRD',
        id: '148',
    },
    {
        name: 'Campile',
        StationAlias: '',
        lat: '52.2855',
        lon: '-6.93896',
        code: 'CPILE',
        id: '52',
    },
    {
        name: 'Ballycullane',
        StationAlias: '',
        lat: '52.2834',
        lon: '-6.83958',
        code: 'BCLAN',
        id: '53',
    },
    {
        name: 'Rosslare Strand',
        StationAlias: '',
        lat: '52.2726',
        lon: '-6.39254',
        code: 'RLSTD',
        id: '58',
    },
    {
        name: 'Tralee',
        StationAlias: '',
        lat: '52.271',
        lon: '-9.69846',
        code: 'TRLEE',
        id: '28',
    },
    {
        name: 'Wellingtonbridge',
        StationAlias: '',
        lat: '52.2678',
        lon: '-6.75392',
        code: 'WBDGE',
        id: '54',
    },
    {
        name: 'Waterford',
        StationAlias: '',
        lat: '52.2667',
        lon: '-7.1183',
        code: 'WFORD',
        id: '50',
    },
    {
        name: 'Rosslare Europort',
        StationAlias: 'Rosslare Harbour',
        lat: '52.2531',
        lon: '-6.33493',
        code: 'RLEPT',
        id: '60',
    },
    {
        name: 'Bridgetown',
        StationAlias: '',
        lat: '52.2312',
        lon: '-6.54918',
        code: 'BRGTN',
        id: '56',
    },
    {
        name: 'Farranfore',
        StationAlias: '',
        lat: '52.1733',
        lon: '-9.55278',
        code: 'FFORE',
        id: '27',
    },
    {
        name: 'Mallow',
        StationAlias: '',
        lat: '52.1396',
        lon: '-8.65521',
        code: 'MLLOW',
        id: '21',
    },
    {
        name: 'Banteer',
        StationAlias: '',
        lat: '52.1287',
        lon: '-8.89793',
        code: 'BTEER',
        id: '23',
    },
    {
        name: 'Rathmore',
        StationAlias: '',
        lat: '52.0854',
        lon: '-9.21756',
        code: 'RMORE',
        id: '25',
    },
    {
        name: 'Millstreet',
        StationAlias: '',
        lat: '52.0776',
        lon: '-9.06973',
        code: 'MLSRT',
        id: '24',
    },
    {
        name: 'Killarney',
        StationAlias: '',
        lat: '52.0595',
        lon: '-9.50198',
        code: 'KLRNY',
        id: '26',
    },
    {
        name: 'Midleton',
        StationAlias: '',
        lat: '51.9212',
        lon: '-8.17579',
        code: 'MDLTN',
        id: '68',
    },
    {
        name: 'Carrigtwohill',
        StationAlias: '',
        lat: '51.9163',
        lon: '-8.26323',
        code: 'CGTWL',
        id: '67',
    },
    {
        name: 'Glounthaune',
        StationAlias: '',
        lat: '51.9112',
        lon: '-8.3254',
        code: 'GHANE',
        id: '380',
    },
    {
        name: 'LittleIsland',
        StationAlias: 'Little Island',
        lat: '51.9078',
        lon: '-8.35466',
        code: 'LSLND',
        id: '61',
    },
    {
        name: 'Cork',
        StationAlias: '',
        lat: '51.9018',
        lon: '-8.4582',
        code: 'CORK',
        id: '30',
    },
    {
        name: 'Fota',
        StationAlias: '',
        lat: '51.896',
        lon: '-8.3183',
        code: 'FOTA',
        id: '63',
    },
    {
        name: 'Carrigaloe',
        StationAlias: '',
        lat: '51.8688',
        lon: '-8.32417',
        code: 'CGLOE',
        id: '64',
    },
    {
        name: 'Rushbrooke',
        StationAlias: '',
        lat: '51.8496',
        lon: '-8.32252',
        code: 'RBROK',
        id: '65',
    },
    {
        name: 'Cobh',
        StationAlias: '',
        lat: '51.8491',
        lon: '-8.29956',
        code: 'COBH',
        id: '66',
    },
];
